introduce Infinity as atom to handle division by 0
pubrrr/lyng pull request #12
Opened 2021-05-08 13:05 UTC by pubrrr

2021-05-08 16:33 UTC, ekinimo requested changes
also maybe fix infinity in parser ? if we cant parse the result because its too big simply return infinity ?

2021-05-08 16:33 UTC, ekinimo commented on src/domain/expression_tree.rs
> +            (Infinity, _) | (_, Infinity) | (NegativeInfinity, _) | (_, NegativeInfinity) => Infinity,
-infinity + x = infinity !!!??

2021-05-08 16:33 UTC, ekinimo commented on src/domain/expression_tree.rs
> +            (Infinity, _) | (_, Infinity) | (NegativeInfinity, _) | (_, NegativeInfinity) => Infinity,
same problem

2021-05-08 16:33 UTC, ekinimo commented on src/domain/expression_tree.rs
> +            (Infinity, _) | (_, Infinity) | (NegativeInfinity, _) | (_, NegativeInfinity) => Infinity,
also here

2021-05-08 16:33 UTC, ekinimo commented on src/domain/expression_tree.rs
> +            (Infinity, NegativeInfinity) | (NegativeInfinity, Infinity) => NegativeInfinity,
mazbe introduce NaN. infinity/infinity is not necerraly infinity

2021-05-13 18:46 UTC, closed without merging

2021-05-13 18:48 UTC, pubrrr commented
This solution does not seem to bring much benefit...