Parser
pubrrr/lyng pull request #5
Opened 2021-04-30 19:53 UTC by ekinimo

2021-05-01 11:46 UTC, pubrrr requested changes

2021-05-01 11:46 UTC, pubrrr commented on src/domain/expression_tree.rs
> +    BinaryOperation(BinaryOperation),
Maybe rather call it BinaryOperator?

2021-05-01 11:46 UTC, pubrrr commented on src/domain/expression_tree.rs
> +    Sum(Box<Expression>,Box<Expression>),
why does it need to be boxed?

2021-05-01 11:46 UTC, pubrrr commented on src/domain/expression_tree.rs
> +            Expression::BinaryOperation(binop) => binop.evaluate(),
binary_operator :P

- [ ] rename

2021-05-01 11:46 UTC, pubrrr commented on src/domain/expression_tree.rs
> +            BinaryOperation::Sum(left_expr,right_expr) => left_expr.evaluate() + right_expr.evaluate(),
I would also be fine with just calling it left and right. I don't like abbreviations :D

2021-05-01 11:46 UTC, pubrrr commented on src/domain/expression_tree.rs
> +
Remove blank line

- [ ] remove

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +    ($fun_name:ident,$ast_member:expr ,$token_name:path,$left_parser:expr,$right_parser:expr) => {
Do you have autoformatting in emacs? :P

- [ ] format

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +            println!(" binary parser {:?}", tokens);
Do we need that? ;)

- [ ] remove?

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +            let right_parseresult = if let Some($token_name) = tokens.last() {
rather use match?

- [ ] consider

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +            //    0 => Err("?????".to_string()),
Seems like this could be deleted?

- [ ] remove comment

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +macro_rules! BinaryParserGenerator {
IntelliJ tells me that it should have a snake case name...

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +        let result = match last_elem  {
I think result can be inlined?

- [ ] check

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +                    (_, _) => Integer(0), //what to do here ?
This should not happen? Return an error?

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +
remove blank lines

- [ ] remove

2021-05-01 11:46 UTC, pubrrr commented on src/infrastructure/parser.rs
> +    fn mul_three(){
multiply_three

- [ ] rename (also other tests)

2021-05-01 12:21 UTC, ekinimo commented on src/domain/expression_tree.rs
> +    Sum(Box<Expression>,Box<Expression>),
You cant have recursive types. Rust compiler needs to  now how big a structure is gonna be during compile time
if i have struct Foo{ arg : Foo} i cxant decide how big foo is. the situation is essentiallz the same i believe

2021-05-01 12:21 UTC, ekinimo commented on src/domain/expression_tree.rs
> +            BinaryOperation::Sum(left_expr,right_expr) => left_expr.evaluate() + right_expr.evaluate(),
old c habbits die hard :D

2021-05-01 12:22 UTC, ekinimo commented on src/infrastructure/parser.rs
> +    ($fun_name:ident,$ast_member:expr ,$token_name:path,$left_parser:expr,$right_parser:expr) => {
well on the production machine i have autoformatting on the laptop i dont but on the big machine i havent set it up to autoformat everztime i save it. Should probablz do that :D

2021-05-01 12:22 UTC, ekinimo commented on src/infrastructure/parser.rs
> +            println!(" binary parser {:?}", tokens);
you mean the println! ?

2021-05-01 12:23 UTC, ekinimo commented on src/infrastructure/parser.rs
> +        let result = match last_elem  {
what dyou mean ?

2021-05-01 12:23 UTC, ekinimo commented on src/infrastructure/parser.rs
> +                    (_, _) => Integer(0), //what to do here ?
well if your integer is too big to fit the i32 it could happen . But ok ill return an error here

2021-05-01 12:56 UTC, ekinimo commented on src/infrastructure/parser.rs
> +            let right_parseresult = if let Some($token_name) = tokens.last() {
couldnt manage that

2021-05-02 08:57 UTC, pubrrr commented on src/domain/expression_tree.rs
> +    Sum(Box<Expression>,Box<Expression>),
Ah, and before it didn't complain because it was a Vec<Expression>? And there it is also kind of "boxed"?

2021-05-02 08:57 UTC, pubrrr commented on src/infrastructure/parser.rs
> +        let result = match last_elem  {
You have 
let result = ...;
result

you could just directly return result.

2021-05-02 12:24 UTC, pubrrr approved these changes

2021-05-02 12:24 UTC, pubrrr commented on src/infrastructure/parser.rs
> +            let right_parseresult = if let Some($token_name) = tokens.last() {
I think 
```
            let right_parseresult = match tokens.last() {
                Some($token_name) => {
                    tokens.pop();
                    $right_parser(&mut *tokens)?
                },
                _ => return Ok(left_parseresult)
            };
```
should do the job

2021-05-02 12:44 UTC, pubrrr commented on src/infrastructure/parser.rs
> +            _ => Err("Parse error".to_string()),
Do we have information at this point to give a some more meaningful error messge?

- [ ] check

2021-05-02 14:01 UTC, merged